export const HIDDEN_MESSAGE_IDS = new Set<string>([
  'HEADER.STAGE.C',
  'RISCI.STRESS.MID',
  'RISCI.COPING.MID',
  'SMA.PLANNING.MID',
  'SMA.REFRAMING.MID',
  'SMA.HEALTHY.MID',
  'SE.MID',
  'DB.PROS_LOW.CONS_HIGH',
  'PROC.EXP.MID',
]);
